---
- name: Configure a SUSE Enterprise Store cluster
  hosts: ses

  tasks:

      - name: update all packages
        zypper: 
            name='*'
            state=latest

      - name: install common packages
        zypper: 
            name='jq'
            state=latest

      - name: get SLES register status
        shell: SUSEConnect --status | jq '.[] | select(.identifier=="SLES") | .subscription_status' | tr -d \"
        register: regstatus

      - name: register node
        command: SUSEConnect -r {{SLES12SP3_regcode}}
        when: regstatus.stdout != "ACTIVE"

      - name: get SES register status
        shell: SUSEConnect --status | jq '.[] | select(.identifier=="ses") | .subscription_status' | tr -d \"
        register: regstatus
        
      - name: register SES extension
        command: SUSEConnect -p ses/5/x86_64 -r {{SES5_regcode}}
        when: regstatus.stdout != "ACTIVE"
        
      - name: enable and start NTP service
        systemd:
          name: ntpd
          enabled: yes
          state: started
      
      - name: install salt packages on salt master
        zypper: 
            name: ['salt-master', 'salt-minion']
            state: latest
        when: ses_role == "master"
      
      - name: start salt master service
        systemd:
            name: salt-master
            enabled: yes
            state: started
        when: ses_role == "master"
      
      - name: install salt packages on minion
        zypper: 
            name='salt-minion'
            state=latest
        when: ses_role == "minion"

      - name: configure salt master in the minion
        lineinfile:
            path: /etc/salt/minion 
            line: "master: {{hostvars[salt_master]['ansible_facts']['fqdn']}}"
            create: yes
      
      - name: start and enable salt minion service
        systemd:
            name: salt-minion
            enabled: yes
            state: restarted

      - name: start and enable salt master service
        systemd:
            name: salt-master
            enabled: yes
            state: restarted
        when: ses_role == "master"

      - name: salt master accept all minions
        command: salt-key --accept-all -y
        when: ses_role == "master"

      - name: install deepsea
        zypper:
            name='deepsea'
            state=latest
        when: ses_role == "master"

      - name: configure deepsea minions target
        lineinfile:
            path: /srv/pillar/ceph/deepsea_minions.sls
            regexp: '^deepsea_minions:'
            insertafter: '^#deepsea_minions:'
            line: "deepsea_minions: \"*\""
        when: ses_role == "master"

      - name: configure deepsea master target
        lineinfile:
            path: /srv/pillar/ceph/master_minion.sls
            regexp: '^master_minion:'
            line: "master_minion: {{hostvars[salt_master]['ansible_facts']['fqdn']}}"
        when: ses_role == "master"

      - name: run preparation deepsea stage
        command: salt-run state.orch ceph.stage.prep
        when: ses_role == "master"

      - name: run discovery deepsea stage
        command: salt-run state.orch ceph.stage.discovery
        when: ses_role == "master"
