---
- name: configure reverse proxies
  become: yes
  with_items: '{{load_balancer["reverse_proxy"]}}'
  template:
    src: reverse_proxy.conf.j2
    dest: "/etc/nginx/conf.d/{{ item['name'] }}.conf"
    owner: root
    group: root
    mode: '0644'
    backup: yes
