---
- name: create directory for the stream configuration
  file:
      path: "/etc/nginx/stream.d"
      state: directory

- name: configure stream module
  template:
    src: stream.conf.j2
    dest: "/etc/nginx/stream.d/{{load_balancer['stream']['name']}}.conf"
    owner: root
    group: root
    mode: '0644'
    backup: yes
