---
- name: Install rsyslog
  become: yes
  zypper:
    name: 'rsyslog'
    state: latest

- import_tasks: enable_rsyslog_tcp_input.yml
  when: ENABLE_TCP_INPUT

- import_tasks: forward_journal_logs.yml
  when: ENABLE_JOURNAL_FORWARD

- name: enable and start rsyslog
  become: yes
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes

