---
- name: Create vms
  debug:
      msg: "{{ vm }}"

- name: Create VMs disk
  shell: virt-builder
    --format qcow2
    {{vm.node_os}}
    --hostname {{vm.name}}{{item}}
    -o {{vm.name}}{{item}}.qcow2
    --root-password password:{{vm.root_password}}
    --ssh-inject root:file:/tmp/vm_ssh_key
    --network
  with_sequence: count={{vm.count}} start=0

- name: Create VM volumes
  become: yes
  shell: virsh vol-create-as
    {{vm.vm_pool}}
    {{vm.name}}{{item}}
    {{vm.disk}}
    --format qcow2
  with_sequence: count={{vm.count}} start=0

- name: Upload disk content to the VM volume
  become: yes
  shell: virsh vol-upload
    --pool {{vm.vm_pool}}
    {{vm.name}}{{item}}
    {{vm.name}}{{item}}.qcow2
  with_sequence: count={{vm.count}} start=0

- name: Launch VM
  become: yes
  shell: virt-install 
    --import
    --name {{vm.name}}{{item}}
    --ram={{vm.memory}}
    --vcpus={{vm.cpus}}
    --disk vol={{vm.vm_pool}}/{{vm.name}}{{item}}
    --boot hd,menu=on 
    --network network={{vm.network}},model=virtio
    --os-variant={{vm.os_variant}}
    --noautoconsole
  with_sequence: count={{vm.count}} start=0

- name: Removes temporary VM disks
  file:
      state: absent
      path: "{{vm.name}}{{item}}.qcow2"
  with_sequence: count={{vm.count}} start=0

