---
- name: Copy SSH public key
  copy:
    src: "{{SSH_KEY_VM}}"
    dest: /tmp/vm_ssh_key
    mode: '600'

- name: Create VMS
  include_tasks: create-vm.yml
  with_items:
      - "{{ vms }}"
  loop_control:
      loop_var: vm

- name: Delete the public ssh key
  file:
    state: absent
    path: /tmp/vm_ssh_key
