---

- name: Enable and start libvirtd
  become: yes
  systemd:
    name: libvirtd
    state: started
    enabled: yes

- import_tasks: delete-cluster.yml
  when: RECREATE_CLUSTER | bool
- import_tasks: create-cluster.yml
  when: RECREATE_CLUSTER | bool

- pause:
    seconds: 30
  when: RECREATE_CLUSTER | bool

- meta: refresh_inventory
