- name: Register CaaSP
  become: yes
  shell: "SUSEConnect -r {{ CAASP_REGISTRATION_CODE }}"

- name: Register server application modue
  become: yes
  shell: "SUSEConnect --product sle-module-server-applications/15.1/x86_64"

- name: Register SUSE Linux Enterprise High Availability Extension
  become: yes
  shell: "SUSEConnect --product sle-ha/15.1/x86_64 -r {{ HA_REGISTRATION_CODE }}"

- name: Install HAProxy
  become: yes
  zypper: 
    name: haproxy
    state: present

- name: Update HAProxy config file
  become: yes
  template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      backup: yes

- name: Add port 6443 in the firewall public zone
  become: yes
  shell: "firewall-cmd --zone=public --permanent --add-port=6443/tcp"

- name: Add port 32000 in the firewall public zone
  become: yes
  shell: "firewall-cmd --zone=public --permanent --add-port=32000/tcp"

- name: Add port 32001 in the firewall public zone
  become: yes
  shell: "firewall-cmd --zone=public --permanent --add-port=32001/tcp"

- name: Add port 9000 in the firewall public zone
  become: yes
  shell: "firewall-cmd --zone=public --permanent --add-port=9000/tcp"

- name: Reload firewall
  become: yes
  shell: "firewall-cmd --reload"

- name: Start and enable HAProxy
  become: yes
  systemd:
      name: haproxy
      state: restarted
      enabled: yes
