---
- name: install the workstation environment
  hosts: workstation
  become: yes
  vars:
          home: "{{ lookup('env', 'HOME') }}"
          user: "{{ lookup('env', 'USER') }}"

  tasks:
          - name: install zypper packages
            zypper: name={{item}} state=latest
            when: ansible_distribution == "openSUSE Leap"
            with_items:
                    - autoconf
                    - automake
                    - clang
                    - ctags
                    - curl
                    - doxygen
                    - flatpak
                    - gcc
                    - gcc-c++
                    - gdb
                    - git-core
                    - git-email
                    - go
                    - htop
                    - make
                    - meson
                    - ninja
                    - python-pip
                    - qemu
                    - strace
                    - tmux
                    - unzip
                    - valgrind
                    - vim
                    - virt-manager
                    - wget
                    - perl-Net-SMTP-SSL
                    - perl-Authen-SASL

          - name: clone the dotfiles repository
            git:
                    repo: 'git@github.com:jvanz/dotfiles.git'
                    dest: '{{ home }}/dotfiles'
            become: no
            
          - name: install configuration files
            become: no
            file:
                    src: '{{ home }}/dotfiles/{{ item.src }}'
                    dest: '{{ home }}/{{ item.dest }}'
                    state: link
                    force: yes
                    owner: '{{ user }}'
            with_items:
                    - { src: '.vim', dest: '.vim' }
                    - { src: 'tmux/.tmux.conf', dest: '.tmux.conf' }
                    - { src: '.gitconfig', dest: '.gitconfig' }

          - name: update bashrc
            become: no
            lineinfile:
                    path: '{{ home }}/.bashrc'
                    line:  'source {{ home }}/dotfiles/.bashrc'

          - name: install python pip packages
            become: no
            pip:
                    state: latest
                    name: "{{ item }}"
                    extra_args: --user
                    executable: pip3
            with_items:
                    - meson
