---
- name: install the workstation environment
  hosts: server-workstation
  become: no
  vars:
          user_home: "~"

  tasks:
          - debug:
                  msg: "Target distribution: {{ ansible_distribution }}"

          - name: extract dotfiles repo
            unarchive:
                src: 'dotfiles.zip'
                dest: '{{ user_home }}'

          - name: remove old dotfiles version
            file: 
                path: '{{ user_home }}/dotfiles'
                state: absent

          - name: rename dotfiles directory
            command: mv '{{ user_home }}/dotfiles-master' '{{ user_home }}/dotfiles'

          - name: remove dotfile zip file
            file: 
                path: '{{ user_home }}/dotfiles.zip'
                state: absent

          - name: update bashrc
            lineinfile:
                path: '{{ user_home }}/.bashrc'
                line:  'source {{ user_home }}/dotfiles/.bashrc'

          - name: install vim files
            file:
                src: '{{ user_home }}/dotfiles/.vim'
                dest: '{{ user_home }}/.vim'
                state: link

          - name: create link to .vimrc configuration files
            file:
                src: '{{ user_home }}/.vim/vimrc'
                dest: '{{ user_home }}/.vimrc'
                state: link

          - name: update vim plugins url
            when: ansible_distribution == "SLES"
            replace:
                    path: '{{ user_home }}/.vim/vimrc'
                    regexp: "Plug '"
                    replace: "Plug 'git@github.com:"

          - name: create a link to tmux.conf file
            file:
                src: '{{ user_home }}/dotfiles/.tmux.conf'
                dest: '{{ user_home }}/.tmux.conf'
                state: link

