- name: install the python-xml lib needed to ansible works
  command: zypper install -y python-xml
  become: yes
  when: ansible_distribution == "openSUSE Leap" or ansible_distribution == "openSUSE Tumbleweed"

- name: update all package
  when: ansible_distribution == "openSUSE Leap" or ansible_distribution == "openSUSE Tumbleweed"
  become: yes
  zypper:
    name: '*'
    state: latest

- name: apply all patches
  when: ansible_distribution == "openSUSE Leap" or ansible_distribution == "openSUSE Tumbleweed"
  become: yes
  zypper:
    name: '*'
    state: latest
    type: patch

- name: install zypper packages
  zypper: name={{item}} state=latest
  when: ansible_distribution == "openSUSE Leap" or ansible_distribution == "openSUSE Tumbleweed"
  become: yes
  with_items:
          - autoconf
          - automake
          - clang
          - ctags
          - curl
          - deja-dup
          - doxygen
          - flatpak
          - gcc
          - gcc-c++
          - gdb
          - git-core
          - git-email
          - go
          - htop
          - make
          - meson
          - neomutt
          - ninja
          - osc
          - perl-Authen-SASL
          - perl-Net-SMTP-SSL
          - python-pip
          - qemu
          - strace
          - taskwarrior
          - tmux
          - unzip
          - valgrind
          - vim
          - virt-manager
          - wget

- name: clone the dotfiles repository
  git:
          repo: 'git@github.com:jvanz/dotfiles.git'
          dest: '{{ home }}/dotfiles'

- name: install configuration files
  file:
          src: '{{ home }}/dotfiles/{{ item.src }}'
          dest: '{{ home }}/{{ item.dest }}'
          state: link
          force: yes
          owner: '{{ user }}'
  with_items:
          - { src: '.vim', dest: '.vim' }
          - { src: '.tmux.conf', dest: '.tmux.conf' }
          - { src: '.gitconfig', dest: '.gitconfig' }
          - { src: 'taskrc', dest: '.taskrc' }

- name: update bashrc
  lineinfile:
          path: '{{ home }}/.bashrc'
          line:  'source {{ home }}/dotfiles/.bashrc'

- name: install python pip packages
  pip:
          state: latest
          name: "{{ item }}"
          extra_args: --user
          executable: pip3
  with_items:
          - meson
          - bugwarrior
