---
- name: install etcd
  package: name=etcd state=present

- name: copy apiserver file
  copy: src=apiserver dest=/etc/kubernetes/apiserver

- name: update etcd.conf
  lineinfile: dest=/etc/etcd/etcd.conf regexp='^ETCD_LISTEN_CLIENT_URLS=.*$'
              line='ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"'
              state=present

- name: create kubernetes directory
  file: path=/var/run/kubernetes state=directory mode=750 owner=kube group=kube

- name: restart etcd
  service: name=etcd enabled=yes state=restarted

- name: restart kube-apiserver
  service: name=kube-apiserver enabled=yes state=restarted

- name: restart kube-controller-manager
  service: name=kube-controller-manager enabled=yes state=restarted

- name: restart kube-scheduler
  service: name=kube-scheduler enabled=yes state=restarted

- name: copy node.json file
  template: src=node.json.j2 dest=/tmp/node.json

- name: create node object internally in kubernetes
  command: kubectl create -f /tmp/node.json

