- debug:
    msg: "Target distribution: {{ ansible_distribution }}"

- debug:
    msg: "Target distribution: {{ ansible_facts['distribution_major_version'] }}"

- import_tasks: suse_tasks.yml
  when: ansible_distribution == "openSUSE Leap" or ansible_distribution == "openSUSE Tumbleweed" or ansible_distribution == "SLES"

- import_tasks: fedora_tasks.yml
  when: ansible_distribution == "Fedora"

