- import_tasks: suse_registration.yaml
  when: REGISTER_MACHINE == True

- name: install the python-xml lib needed to ansible works
  command: zypper install -y python-xml
  become: yes

- name: update all package
  become: yes
  zypper:
    name: '*'
    state: latest

- name: apply all patches
  become: yes
  zypper:
    name: '*'
    state: latest
    type: patch

- name: check if already have the SUSE CA repo installed
  shell: zypper lr -dU | grep --quiet "suse.de/ibs/SUSE:/CA"
  register: zpcmd
  ignore_errors: True

- debug:
    msg: "CA repo already present"
  when: "zpcmd.rc == 0"

- debug:
    msg: "No CA repo found"
  when: "zpcmd.rc != 0"

- name: add missing SUSE CA repo
  become: yes
  command: zypper ar http://download.suse.de/ibs/SUSE:/CA/SLE_{{ansible_distribution_major_version}}_SP{{ansible_distribution_release}}/SUSE:CA.repo
  when: "zpcmd.rc != 0"

- name: refresh repos
  become: yes
  command: zypper --gpg-auto-import-keys ref
  when: "zpcmd.rc != 0"
