---
- name: prepare salt master 
  hosts: salt-master

  tasks:
          - debug:
                  msg: "Target distribution: {{ ansible_distribution }}"

          - name: install salt packages
            zypper: name={{item}} state=latest
            when: ansible_distribution == "SLES"
            with_items:
                    - salt
                    - salt-master

          - name: enable salt master service
            service:
                name: salt-master
                enabled: yes

          - name: restart salt master
            service:
                name: salt-master
                state: restarted

# The firewalld module is not working in the current ansible version on
# openSUSE Leap 15. Need to wait for the fix. 
# https://github.com/ansible/ansible/issues/38161
#          - name: add salt-master in the firewalld 
#            firewalld:
#                service: salt-master
#                permanent: yes
#                state: enabled
#                immediate: yes
# Disable firewalld to test salt. XXX Adds the service in the firewalld when
# the bug is fixed
#
          - name: stop firewalld
            service:
                name: firewalld
                state: stopped

          - name: accept all pending minion
            command: salt-key --accept-all --yes
