- name: install offlineimap and packages used by e-mail
  zypper: name={{item}} state=latest
  when: ansible_distribution == "openSUSE Leap" or ansible_distribution == "openSUSE Tumbleweed"
  become: yes
  with_items:
    - libsecret-tools
    - neomutt
    - offlineimap
    - python2-gobject

- name: create .offlineimap folder in the home directory
  become: no
  file:
    path: "{{ home }}/.offlineimap"
    state: directory

- name: copy python script used to get password and other infos
  become: no
  copy:
    src: gkgetsecret.py
    dest: "{{ home }}/.offlineimap/gkgetsecret.py"

- name: install offlineimap configuration file
  become: no
  template:
    src: offlineimaprc.j2
    dest: "{{ home }}/.offlineimaprc"

- name: create mutt folder
  file:
    path: "{{ home }}/.mutt"
    state: directory

- name: create accounts folder
  file:
    path: "{{ home }}/.mutt/accounts"
    state: directory

- name: install mutt config file
  template:
    src: "muttrc.j2"
    dest: "{{ home }}/.muttrc"

- name: install accounts configuration
  template:
    src: acc.j2
    dest: "{{ home }}/.mutt/accounts/{{ item['key'] }}"
  loop: "{{ emails|dict2items }}"
